global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "pulsesphere-services"
    static_configs:
      - targets:
          - "gateway:8080"
          - "auth:8081"
          - "messaging:8082"
          - "realtime:8083"
          - "media:8084"
          - "search:8085"
          - "notifications:8086"
